import 'data_item_ref.dart';
import 'json_constants.dart';
import 'layout.dart';

/// One stable reference inside the persistent layout stack.
///
/// Purpose:
/// Represents a single ordered layout contribution so callers can remove or
/// reorder stack entries without relying on duplicate-prone layout names.
class LayoutStackEntry {
  final String entryId;
  final DataItemRef layoutRef;

  /// Create a typed layout-stack entry wrapper.
  ///
  /// Parameters:
  /// - `entryId`: Stable identifier assigned by Epiphany for this stack entry.
  /// - `layoutRef`: Reference to the stored layout used by this entry.
  ///
  /// Return value:
  /// - A new immutable `LayoutStackEntry`.
  ///
  /// Requirements:
  /// - `entryId` must be non-empty.
  /// - `layoutRef` must refer to a valid layout namespace/name pair.
  ///
  /// Guarantees:
  /// - The created object preserves the provided entry identity and layout
  ///   reference exactly.
  ///
  /// Invariants:
  /// - Constructing this value does not contact Epiphany or mutate storage.
  const LayoutStackEntry({
    required this.entryId,
    required this.layoutRef,
  });

  /// Serialize this entry to the Epiphany wire format.
  ///
  /// Parameters:
  /// - None.
  ///
  /// Return value:
  /// - A JSON map containing `entryId` and `layoutRef`.
  ///
  /// Requirements:
  /// - `entryId` and `layoutRef` must already satisfy the constructor rules.
  ///
  /// Guarantees:
  /// - Returned JSON preserves the current entry ID and referenced namespace.
  ///
  /// Invariants:
  /// - Serialization is read-only and leaves this object unchanged.
  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      JsonFields.ENTRY_ID: entryId,
      JsonFields.LAYOUT_REF: layoutRef.toJson(),
    };
  }

  /// Parse a layout-stack entry from Epiphany JSON.
  ///
  /// Parameters:
  /// - `json`: Wire-format map containing `entryId` and `layoutRef`.
  ///
  /// Return value:
  /// - A parsed `LayoutStackEntry`.
  ///
  /// Requirements:
  /// - `json` must contain a string `entryId`.
  /// - `json` must contain a valid `layoutRef` object.
  ///
  /// Guarantees:
  /// - The parsed object reflects the server-provided ordering identity and
  ///   layout reference.
  ///
  /// Invariants:
  /// - Parsing does not touch subscription state or remote data.
  factory LayoutStackEntry.fromJson(Map<String, dynamic> json) {
    return LayoutStackEntry(
      entryId: json[JsonFields.ENTRY_ID] as String,
      layoutRef: DataItemRef.fromJson(
        json[JsonFields.LAYOUT_REF] as Map<String, dynamic>,
      ),
    );
  }
}

/// Snapshot of the ordered layout stack and its resolved composed layout.
///
/// Purpose:
/// Gives clients the stack specification they can manipulate plus the resolved
/// layout product that consumers such as Monolith can use directly.
class LayoutStackSnapshot {
  final List<LayoutStackEntry> entries;
  final Layout? resolvedLayout;

  /// Create a typed snapshot of the current layout stack state.
  ///
  /// Parameters:
  /// - `entries`: Ordered stack entries from bottom to top.
  /// - `resolvedLayout`: Optional resolved composed layout generated by Epiphany.
  ///
  /// Return value:
  /// - A new immutable `LayoutStackSnapshot`.
  ///
  /// Requirements:
  /// - `entries` must already be in the intended server order.
  ///
  /// Guarantees:
  /// - The snapshot preserves entry ordering and any resolved layout payload
  ///   supplied by the server.
  ///
  /// Invariants:
  /// - Constructing this value does not mutate stack state or subscribe.
  const LayoutStackSnapshot({
    required this.entries,
    required this.resolvedLayout,
  });

  /// Parse a snapshot from the Epiphany layout-stack schema.
  ///
  /// Parameters:
  /// - `json`: Wire-format map containing stack entries and optional
  ///   `resolvedLayout`.
  ///
  /// Return value:
  /// - A parsed `LayoutStackSnapshot`.
  ///
  /// Requirements:
  /// - `json` must be shaped like the `layoutStack` object returned by Epiphany.
  ///
  /// Guarantees:
  /// - Parsed entry order matches the order encoded in `json`.
  /// - `resolvedLayout` is `null` when the server omits it.
  ///
  /// Invariants:
  /// - Parsing is read-only and does not alter local or remote layout state.
  factory LayoutStackSnapshot.fromJson(Map<String, dynamic> json) {
    final List<dynamic> rawEntries =
        json[JsonFields.LAYOUT_STACK_ENTRIES] as List<dynamic>? ?? <dynamic>[];

    return LayoutStackSnapshot(
      entries: rawEntries
          .map((dynamic entryJson) => LayoutStackEntry.fromJson(
                entryJson as Map<String, dynamic>,
              ))
          .toList(),
      resolvedLayout: json[JsonFields.RESOLVED_LAYOUT] == null
          ? null
          : Layout.fromJson(
              json[JsonFields.RESOLVED_LAYOUT] as Map<String, dynamic>,
            ),
    );
  }
}
