name: hello_dogpaw
description: "Minimal Dog Paw teaching example"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dogpaw:
    path: ../../../packages/dogpaw
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.7
flutter:
  uses-material-design: true
